# Generated by Django 6.0.7 on 2026-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='followup_method',
            field=models.CharField(choices=[('CALL', 'تماس تلفنی'), ('WHATSAPP', 'واتساپ'), ('SMS', 'پیامک'), ('TELEGRAM', 'تلگرام'), ('IN_PERSON', 'حضوری'), ('OTHER', 'سایر روش\u200cها')], default='CALL', max_length=50, verbose_name='روش پیگیری'),
        ),
    ]
