# Generated by Django 6.0.7 on 2026-09-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_supplier_sales_manager_phone_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interested_products',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محصولات مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='potential_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ احتمالی خرید (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='نام کالا/توضیحات محصول'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد/مدل محصول')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه (تومان)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.supplier', verbose_name='تولیدکننده')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.supplierproduct', verbose_name='محصول انتخابی'),
        ),
    ]
