# Generated by Django 6.0.7 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customer_interested_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='interested_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_customers', to='dashboard.supplierproduct', verbose_name='محصول مورد علاقه (انتخابی)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='dashboard.supplier', verbose_name='تولیدکننده مدنظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='interested_products',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محصولات مورد علاقه (متنی)'),
        ),
    ]
