# Generated by Django 5.2.17 on 2026-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_task_customer_followup_time_alter_activitylog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', '🔴 بالا'), ('MEDIUM', '🟡 متوسط'), ('LOW', '🟢 پایین')], default='MEDIUM', max_length=10, verbose_name='اولویت'),
        ),
    ]
