# Generated by Django 5.2.17 on 2026-09-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='interested_products',
        ),
        migrations.AddField(
            model_name='customer',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد / مدل محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='کد / مدل محصول'),
        ),
    ]
