# Generated by Django 6.0.7 on 2026-07-27 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ورود')),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فروشنده')),
                ('interested_products', models.CharField(max_length=255, verbose_name='محصولات مورد علاقه')),
                ('potential_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ احتمالی خرید')),
                ('purchase_probability', models.IntegerField(default=50, verbose_name='احتمال خرید (درصد)')),
                ('status', models.CharField(choices=[('NEW', 'مشتری جدید / تازه وارد'), ('CHECKING', 'در حال بررسی محصول'), ('LIKED', 'محصول را پسندیده'), ('INVOICE', 'فاکتور صادر شده'), ('DECIDING', 'منتظر تصمیم مشتری'), ('NEED_FOLLOWUP', 'نیاز به پیگیری'), ('FOLLOWED_UP', 'پیگیری انجام شد'), ('BOUGHT', 'مشتری خرید کرد'), ('PAUSED', 'مشتری فعلاً خرید نکرد'), ('CANCELED', 'مشتری منصرف شد'), ('LOST', 'مشتری از دست رفته'), ('WAITING_DELIVERY', 'خرید انجام شده و منتظر تحویل'), ('DELIVERED', 'سفارش تحویل داده شد'), ('POST_PURCHASE_FOLLOWUP', 'مشتری بعد از خرید نیاز به پیگیری دارد')], default='NEW', max_length=30, verbose_name='وضعیت مشتری')),
                ('priority', models.CharField(choices=[('CRITICAL', '🔴 خیلی مهم (آماده خرید/فاکتور/احتمال بالا)'), ('HIGH', '🟠 مهم (پسندیده/بدون تصمیم نهایی)'), ('MEDIUM', '🟡 متوسط (علاقه\u200cمند/در حال بررسی)'), ('LOW', '⚪ کم اهمیت (بدون قصد خرید مشخص)')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('last_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='آخرین اقدام انجام شده')),
                ('last_followup_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین پیگیری')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیگیری بعدی')),
                ('followup_method', models.CharField(default='تماس', max_length=50, verbose_name='روش پیگیری')),
                ('lost_reason', models.TextField(blank=True, null=True, verbose_name='دلیل نخریدن / انصراف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تولیدی / کارگاه')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('sales_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مسئول فروش')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیگیری بعدی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات و وضعیت همکاری')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
                ('action_description', models.TextField(verbose_name='شرح اقدام / تغییر وضعیت')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='نتیجه تماس/اقدام')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.customer', verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='محصول')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='کد/شماره سفارش')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('supplier_order_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت برای تولیدکننده')),
                ('expected_ready_date', models.DateField(blank=True, null=True, verbose_name='تاریخ احتمالی آماده شدن')),
                ('delivery_to_customer_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل به مشتری')),
                ('status', models.CharField(choices=[('REGISTERED', 'سفارش ثبت شد'), ('SENT_TO_SUPPLIER', 'ارسال برای تولیدکننده'), ('SUPPLIER_CONFIRMED', 'تأیید تولیدکننده دریافت شد'), ('IN_PRODUCTION', 'در حال تولید'), ('READY_TO_SHIP', 'آماده ارسال'), ('GIVEN_TO_CARRIER', 'تحویل باربری شد'), ('IN_TRANSIT', 'در مسیر کرمان'), ('ARRIVED_STORE', 'به فروشگاه رسید'), ('READY_FOR_CUSTOMER', 'آماده تحویل به مشتری'), ('DELIVERED', 'تحویل مشتری شد')], default='REGISTERED', max_length=30, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کل سفارش')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پرداخت شده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer', verbose_name='مشتری')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.supplier', verbose_name='تولیدکننده')),
            ],
        ),
    ]
