# Generated by Django 6.0.7 on 2026-08-10 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_customer_followup_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='freight_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل به باربری'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ رسیدن به فروشگاه'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین پیگیری'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='overall_status',
            field=models.CharField(choices=[('ACTIVE', 'فعال و فعالانه'), ('SUSPENDED', 'معلق / موقت'), ('INACTIVE', 'غیرفعال / قطع همکاری')], default='ACTIVE', max_length=20, verbose_name='وضعیت کلی همکاری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پرداخت شده (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'سفارش ثبت شد'), ('SENT_TO_SUPPLIER', 'سفارش برای تولیدکننده ارسال شد'), ('SUPPLIER_CONFIRMED', 'تأیید تولیدکننده دریافت شد'), ('IN_PRODUCTION', 'در حال تولید'), ('READY_TO_SHIP', 'آماده ارسال'), ('GIVEN_TO_CARRIER', 'تحویل باربری شد'), ('IN_TRANSIT', 'در مسیر کرمان'), ('ARRIVED_STORE', 'به فروشگاه رسید'), ('READY_FOR_CUSTOMER', 'آماده تحویل به مشتری'), ('DELIVERED', 'تحویل مشتری شد')], default='REGISTERED', max_length=30, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.supplier', verbose_name='تولیدکننده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ سفارش (تومان)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و یادداشت\u200cها'),
        ),
    ]
