# Generated by Django 6.0.7 on 2026-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_description_order_freight_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sales_manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره همراه مسئول فروش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'سفارش ثبت شد'), ('SENT_TO_SUPPLIER', 'سفارش برای تولیدکننده ارسال شد'), ('SUPPLIER_CONFIRMED', 'تأیید تولیدکننده دریافت شد'), ('IN_PRODUCTION', 'در حال تولید'), ('READY_TO_SHIP', 'آماده ارسال'), ('GIVEN_TO_CARRIER', 'تحویل باربری شد'), ('IN_TRANSIT', 'در مسیر'), ('ARRIVED_STORE', 'به فروشگاه رسید'), ('READY_FOR_CUSTOMER', 'آماده تحویل به مشتری'), ('DELIVERED', 'تحویل مشتری شد')], default='REGISTERED', max_length=30, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='overall_status',
            field=models.CharField(choices=[('ACTIVE', '🟢 فعال و عالی'), ('MEDIUM', '🟡 معمولی'), ('PROBLEM', '🟠 دارای تاخیر / مشکل'), ('SUSPENDED', '⚪ معلق / موقت'), ('INACTIVE', '🔴 غیرفعال / قطع همکاری')], default='ACTIVE', max_length=20, verbose_name='وضعیت کلی همکاری'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس کارگاه'),
        ),
    ]
