# Generated by Django 6.0.7 on 2026-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customer_interested_product_customer_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کار / یادآوری')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('due_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت (HH:MM)')),
                ('priority', models.CharField(choices=[('HIGH', '🔴 بالا'), ('MEDIUM', '🟡 متوسط'), ('LOW', '🟢 پایین')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='انجام شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='interested_products',
        ),
        migrations.AddField(
            model_name='customer',
            name='followup_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت یادآوری بعدی (HH:MM)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد / مدل محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='کد / مدل محصول'),
        ),
    ]
